# Generated by Django 5.0.3 on 2024-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropmenor',
            name='cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='pse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='ptr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
