# Generated by Django 5.0.3 on 2024-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='nacionalidad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='num_hijos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
