# Generated by Django 5.0.3 on 2024-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antropometrico',
            old_name='edad_meses',
            new_name='meses',
        ),
        migrations.RemoveField(
            model_name='antropometrico',
            name='jornada',
        ),
        migrations.AlterField(
            model_name='antropometrico',
            name='riesgo',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='menor',
            name='fecha_ing_proyecto',
            field=models.DateField(null=True),
        ),
    ]
