# Generated by Django 5.0.3 on 2024-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunas',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='vacunas',
            name='dosis',
            field=models.CharField(choices=[('1ra DOSIS', '1ra DOSIS'), ('2da DOSIS', '2da DOSIS'), ('3ra DOSIS', '3ra DOSIS'), ('4ra DOSIS', '4ra DOSIS'), ('5ra DOSIS', '5ra DOSIS'), ('REFUERZO 1ra DOSIS', 'REFUERZO 1ra DOSIS'), ('REFUERZO 2da DOSIS', 'REFUERZO 2da DOSIS'), ('REFUERZO 3ra DOSIS', 'REFUERZO 3ra DOSIS')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacunas',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacunas',
            name='meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='antropbef',
            name='cbi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacunas',
            name='vacuna',
            field=models.CharField(choices=[('Anti Tuberculosis - BCG', 'Anti Tuberculosis - BCG'), ('Anti Hepatitis B - HB', 'Anti Hepatitis B - HB'), ('Anti Poliomielitis - VPI-bVPO', 'Anti Poliomielitis - VPI-bVPO'), ('Anti Difteria, Tétano y Pertussis - DTPc-DTPa', 'Anti Difteria, Tétano y Pertussis - DTPc-DTPa'), ('Anti Haemophilus Influenzae Tipo B - Hib', 'Anti Haemophilus Influenzae Tipo B - Hib'), ('Antirrotavirus - RV1-RV5', 'Antirrotavirus - RV1-RV5'), ('Anti Streptococus Pneumoniae I0 o I3 V - VCN', 'Anti Streptococus Pneumoniae I0 o I3 V - VCN'), ('Anti Influenza', 'Anti Influenza'), ('Anti SRS - SRP1-2', 'Anti SRS - SRP1-2'), ('Anti Amarílica - FA', 'Anti Amarílica - FA'), ('Anti Hepatitis A - HA', 'Anti Hepatitis A - HA'), ('Anti Varicela', 'Anti Varicela'), ('Anti meningococo conjugada A,C,Y,W-135', 'Anti meningococo conjugada A,C,Y,W-135'), ('Anti Streptococcus Pneumoniae 23V', 'Anti Streptococcus Pneumoniae 23V')], max_length=50),
        ),
    ]
