# Generated by Django 5.0.2 on 2024-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-estatus',)},
        ),
        migrations.AlterField(
            model_name='antropometrico',
            name='riesgo',
            field=models.BooleanField(choices=[('1', 'SI'), ('0', 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='embarazada',
            field=models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='lactando',
            field=models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_usuario',
            field=models.CharField(choices=[('MEN', 'MENOR'), ('BEF', 'BENEFICIARIO'), ('EMB', 'EMBARAZADA'), ('LAC', 'LACTANTE')], default='BEF', max_length=3),
        ),
        migrations.AlterField(
            model_name='familia',
            name='sexo',
            field=models.PositiveIntegerField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')]),
        ),
        migrations.AlterField(
            model_name='menor',
            name='sexo',
            field=models.PositiveIntegerField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
