# Generated by Django 5.0.3 on 2024-03-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='condicion',
            new_name='observacion',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='edad_meses',
            new_name='meses',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='condicion',
            new_name='observacion',
        ),
        migrations.RenameField(
            model_name='menor',
            old_name='edad_meses',
            new_name='meses',
        ),
        migrations.RenameField(
            model_name='menor',
            old_name='condicion',
            new_name='observacion',
        ),
        migrations.RemoveField(
            model_name='antropometrico',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='proyecto',
        ),
    ]
