# Generated by Django 5.0.3 on 2024-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_beneficiario_nacionalidad_beneficiario_num_hijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
