# Generated by Django 5.0.3 on 2024-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_alter_beneficiario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropbef',
            name='tiempo_gestacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
