# Generated by Django 5.0.3 on 2024-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_remove_vacunas_descripcion_vacunas_dosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunas',
            name='observacion',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
