# Generated by Django 5.0.3 on 2024-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_rename_condicion_beneficiario_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometrico',
            name='embarazo_lactando',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='educacion',
            field=models.CharField(blank=True, choices=[('ANALFABELO', 'ANALFABETO'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TEC MEDIO', 'TECNICO MEDIO'), ('TEC SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITAQRIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='laboral',
            field=models.CharField(blank=True, choices=[('DESEMPLEADO', 'DESEMPLEADO'), ('EMPLEADO', 'EMPLEADO'), ('OCACIONAL', 'OCACIONAL'), ('INDEPENDIENTE', 'INDEPENDIENTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_cuenta',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='profesion',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
