# Generated by Django 5.0.3 on 2024-07-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_alter_antropmenor_cc_alter_antropmenor_pse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imcembarazada',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='imcembarazada',
            name='p6',
        ),
    ]
