# Generated by Django 5.0.3 on 2024-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0002_rename_fecha_antropbef_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='num_hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='observacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
