# Generated by Django 5.0.3 on 2024-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0003_alter_beneficiario_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropbef',
            name='proyecto',
            field=models.CharField(default='PRIMER PROYECTO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menor',
            name='parentesco',
            field=models.CharField(choices=[('HIJO', 'HIJO'), ('HIJA', 'HIJA'), ('SOBRINO', 'SOBRINO'), ('SOBRINA', 'SOBRINA'), ('NIETO', 'NIETO'), ('NIETA', 'NIETA'), ('ASISTIDO', 'ASISTIDO'), ('ASISTIDA', 'ASISTIDA')], max_length=15),
        ),
    ]
