# Generated by Django 5.0.3 on 2024-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0003_alter_antropbef_tiempo_gestacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medica',
            name='asesoria',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AddField(
            model_name='medica',
            name='lacktokiana',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AddField(
            model_name='medica',
            name='prokids',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AddField(
            model_name='medica',
            name='psicologia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AddField(
            model_name='medica',
            name='recomendacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AddField(
            model_name='medica',
            name='vitaminas',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ALTA', 'ALTA'), ('EGRESO', 'EGRESO'), ('DESINCORPORADO', 'DESINCORPORADO'), ('CERRADO', 'CERRADO')], default='ACTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='menor',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ALTA', 'ALTA'), ('EGRESO', 'EGRESO'), ('DESINCORPORADO', 'DESINCORPORADO'), ('CERRADO', 'CERRADO')], default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ALTA', 'ALTA'), ('EGRESO', 'EGRESO'), ('DESINCORPORADO', 'DESINCORPORADO'), ('CERRADO', 'CERRADO')], max_length=30),
        ),
    ]
