# Generated by Django 5.0.3 on 2024-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0003_antropometrico_embarazo_lactando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropometrico',
            name='embarazo_lactando',
            field=models.CharField(blank=True, choices=[('EMBARAZADA', 'EMBARAZADA'), ('LACTANDO', 'LACTANDO')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='antropometrico',
            name='riesgo',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='embarazada',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='lactando',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familia',
            name='sexo',
            field=models.PositiveIntegerField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='abcesos',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='alergia',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='antiviotico',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='caries',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='cefalea',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='dermatitis',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='desp_familia',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='medica',
            name='desp_menor',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diarreas',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='faringoamigdalitis',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='folico',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='hierro',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='hiperactividad',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='infeccion',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='leche',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='minerales',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='otitis',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='otros',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='parasitosis',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='sano',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='sinusitis',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='traumatismo',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='medica',
            name='vitamina',
            field=models.BooleanField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')]),
        ),
        migrations.AlterField(
            model_name='menor',
            name='sexo',
            field=models.PositiveIntegerField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')]),
        ),
    ]
