# Generated by Django 5.0.3 on 2024-07-05 11:35

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0003_remove_imcembarazada_p1_remove_imcembarazada_p6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricional',
            name='agua_botellon',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='agua_filtrada',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='agua_hervida',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='agua_tableta',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='agua_tuberia',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='bono_entre6',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='clap_entre6',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina_aduelos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina_madre',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina_otro',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina_padre',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='cocina_tios',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='comidas',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='desearia_conocimiento',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='embarazada_ini',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='familia_entre6',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='frecuencia_alimentos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='frutas_acostumbrado',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='frutas_costosos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='frutas_prepararlo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='frutas_rechazo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='gestacion',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_carnes',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_cereales',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_dulces',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_frutas',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_grasas',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupo_leche',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='iglesia_entre6',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='lactancia',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='lactante_ini',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='medicamento_que',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado_abuelos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado_madre',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado_otro',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado_padre',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='mercado_tios',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='pensionado_entre6',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='practica',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='servicio_agua',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='servicio_aseo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='servicio_electricidad',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='servicio_no',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='servicio_telefono',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='vegelales_rechazo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='vegetales_acostumbrado',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='vegetales_costo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='vegetales_prepararlo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='viceras_acostumbrado',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='viceras_costosos',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='viceras_prepararlo',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='viceras_rechazo',
        ),
        migrations.AddField(
            model_name='nutricional',
            name='agua',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tuberia sin Tratamiento', 'Tuberia sin Tratamiento'), ('Filtrada', 'Filtrada'), ('Botellon', 'Botellon'), ('Hervida', 'Hervida'), ('Tabletas de Aguatab', 'Tabletas de Aguatab')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='cocina_lorealiza',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo(a)', 'Abuelo(a)'), ('Tio(a)', 'Tio(a)'), ('Otros', 'Otros')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='cuantas_comidas',
            field=models.CharField(blank=True, choices=[('1 Comida', '1 Comida'), ('2 Comidas', '2 Comidas'), ('3 Comidas', '3 Comidas')], max_length=10),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='cuantos_grupos',
            field=models.CharField(blank=True, choices=[('1 - 2', '1 - 2'), ('2 - 3', '2 - 3'), ('3 - 4', '3 - 4'), ('4 - 6', '4 - 6')], max_length=10),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='desea_conocimiento',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='dificultad_amamantar',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='falla_servicio',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agua', 'Agua'), ('Gas', 'Gas'), ('Eléctricidad', 'Eléctricidad'), ('Telefonía Internet', 'Telefonía Internet'), ('Aseo Urbano', 'Aseo Urbano')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='lactante',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='medicamento_suplemento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='mercado_lorealiza',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo(a)', 'Abuelo(a)'), ('Tio(a)', 'Tio(a)'), ('Otros', 'Otros')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='practica_deporte',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='tiempo_gestacion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='tiempo_lactancia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='tipo_grupos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cereales y Leguminosas', 'Cereales y Leguminosas'), ('Frutas y Verduras', 'Frutas y Verduras'), ('Leche, Yogures y Quesos', 'Leche, Yogures y Quesos'), ('Grasas', 'Grasas'), ('Dulces', 'Dulces'), ('Carnes y Huevos', 'Carnes y Huevos')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='vegelales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Por Rechazo', 'Por Rechazo'), ('No sabe prepararlo', 'No sabe prepararlo'), ('Están muy costosos', 'Están muy costosos'), ('No están acostumbrados', 'No están acostumbrados')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='actividad',
            field=models.CharField(blank=True, choices=[('Juegos Activos', 'Juegos Activos'), ('Práctica Deportiva', 'Práctica Deportiva'), ('Ambas Actividades', 'Ambas Actividades')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='almacena_agua',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='apetito',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Elevado', 'Elevado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='bonos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='bonos_entre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entre 1 a 3 meses', 'Entre 1 a 3 meses'), ('Entre 3 a 6 meses', 'Entre 3 a 6 meses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='carnes',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='cereales',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='charcuteria',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='clap',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='clap_entre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entre 1 a 3 meses', 'Entre 1 a 3 meses'), ('Entre 3 a 6 meses', 'Entre 3 a 6 meses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='compra_agua',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='compra_gas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_beneficio',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_calidad',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información', 'Poca Información')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_desnutricion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información', 'Poca Información')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_grupos',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información', 'Poca Información')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='desea_amamantar',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='desea_orientacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='donde_almacena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pipote', 'Pipote'), ('Tanque', 'Tanque'), ('Otros', 'Otros')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embarazada',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embutidos',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='familiar',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='familiar_entre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entre 1 a 3 meses', 'Entre 1 a 3 meses'), ('Entre 3 a 6 meses', 'Entre 3 a 6 meses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('Diario', 'Diario'), ('2-3 días', '2-3 días'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frutas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Por Rechazo', 'Por Rechazo'), ('No sabe prepararlo', 'No sabe prepararlo'), ('Están muy costosos', 'Están muy costosos'), ('No están acostumbrados', 'No están acostumbrados')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='grasas',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='huevos',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='iglesia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='iglesia_entre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entre 1 a 3 meses', 'Entre 1 a 3 meses'), ('Entre 3 a 6 meses', 'Entre 3 a 6 meses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lactando',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lacteos',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='leguminosas',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='medicamento',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='meriendas',
            field=models.CharField(blank=True, choices=[('1 Merienda', '1 Merienda'), ('2 Meriendas', '2 Meriendas'), ('3 Meriendas', '3 Meriendas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pensionado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pensionado_entre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entre 1 a 3 meses', 'Entre 1 a 3 meses'), ('Entre 3 a 6 meses', 'Entre 3 a 6 meses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pescado',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pollo',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tiempo',
            field=models.CharField(blank=True, choices=[('30 min de 1-3 / 7', '30 min de 1-3 / 7'), ('30 min de 4-7 / 7', '30 min de 4-7 / 7'), ('más de 30 min 1-3 / 7', 'más de 30 min 1-3 / 7'), ('más de 30 min 4-7 / 7', 'más de 30 min 4-7 / 7'), ('No precisa datos', 'No precisa datos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tuberculos',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='vegetales',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='viceras',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Por Rechazo', 'Por Rechazo'), ('No sabe prepararlo', 'No sabe prepararlo'), ('Están muy costosos', 'Están muy costosos'), ('No están acostumbrados', 'No están acostumbrados')], max_length=200),
        ),
    ]
