# Generated by Django 5.0.3 on 2024-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0004_alter_antropbef_cbi_alter_antropbef_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropbef',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='educacion',
            field=models.CharField(blank=True, choices=[('ANALFABETA', 'ANALFABETA'), ('ANALFABETO', 'ANALFABETO'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO MEDIO', 'TECNICO MEDIO'), ('TECNICO SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERA', 'SOLTERA'), ('SOLTERO', 'SOLTERO'), ('CASADA', 'CASADA'), ('CASADO', 'CASADO'), ('DIVORCIADA', 'DIVORCIADA'), ('DIVORCIADO', 'DIVORCIADO'), ('VIUDA', 'VIUDA'), ('VIUDO', 'VIUDO'), ('CONCUBINATO', 'CONCUBINATO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='laboral',
            field=models.CharField(blank=True, choices=[('DESEMPLEADA', 'DESEMPLEADA'), ('DESEMPLEADO', 'DESEMPLEADO'), ('EMPLEADA', 'EMPLEADA'), ('EMPLEADO', 'EMPLEADO'), ('OCACIONAL', 'OCACIONAL'), ('INDEPENDIENTE', 'INDEPENDIENTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='educacion',
            field=models.CharField(choices=[('ANALFABETA', 'ANALFABETA'), ('ANALFABETO', 'ANALFABETO'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO MEDIO', 'TECNICO MEDIO'), ('TECNICO SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERA', 'SOLTERA'), ('SOLTERO', 'SOLTERO'), ('CASADA', 'CASADA'), ('CASADO', 'CASADO'), ('DIVORCIADA', 'DIVORCIADA'), ('DIVORCIADO', 'DIVORCIADO'), ('VIUDA', 'VIUDA'), ('VIUDO', 'VIUDO'), ('CONCUBINATO', 'CONCUBINATO')], max_length=15),
        ),
        migrations.AlterField(
            model_name='familia',
            name='laboral',
            field=models.CharField(blank=True, choices=[('DESEMPLEADA', 'DESEMPLEADA'), ('DESEMPLEADO', 'DESEMPLEADO'), ('EMPLEADA', 'EMPLEADA'), ('EMPLEADO', 'EMPLEADO'), ('OCACIONAL', 'OCACIONAL'), ('INDEPENDIENTE', 'INDEPENDIENTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(choices=[('CONYUGUE', 'CONYUGUE'), ('SOBRINO', 'SOBRINO'), ('SOBRINA', 'SOBRINA'), ('NIETO', 'NIETO'), ('NIETA', 'NIETA'), ('ASISTIDO', 'ASISTIDO'), ('ASISTIDA', 'ASISTIDA'), ('HERMANO', 'HERMANO'), ('HERMANA', 'HERMANA'), ('TIO', 'TIO'), ('TIA', 'TIA'), ('ABUELO', 'ABUELO'), ('ABUELA', 'ABUELA')], max_length=15),
        ),
    ]
