# Generated by Django 5.0.3 on 2024-09-08 12:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0004_medica_asesoria_medica_lacktokiana_medica_prokids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='asesoria',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='lacktokiana',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='prokids',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='psicologia',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='recomendacion',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='vitaminas',
        ),
        migrations.AddField(
            model_name='medica',
            name='recomendaciones1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Suplementación de Acido Folico', 'Suplementación de Acido Folico'), ('Suplementación de Hierro', 'Suplementación de Hierro'), ('Suplementación de Minerales y Vitaminas', 'Suplementación de Minerales y Vitaminas')], max_length=200),
        ),
        migrations.AddField(
            model_name='medica',
            name='recomendaciones2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Suplementación de Acido Folico', 'Suplementación de Acido Folico'), ('Suplementación de Hierro', 'Suplementación de Hierro'), ('Suplementación de Minerales y Vitaminas', 'Suplementación de Minerales y Vitaminas')], max_length=200),
        ),
    ]
