# Generated by Django 5.0.3 on 2024-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0004_alter_antropometrico_embarazo_lactando_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('estatus',)},
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='educacion',
            field=models.CharField(blank=True, choices=[('ANALFABELO', 'ANALFABETO'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TEC MEDIO', 'TECNICO MEDIO'), ('TEC SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='educacion',
            field=models.CharField(choices=[('ANALFABELO', 'ANALFABETO'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TEC MEDIO', 'TECNICO MEDIO'), ('TEC SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(choices=[('SOBRINO', 'SOBRINO'), ('NIETO', 'NIETO'), ('ASISTIDO', 'ASISTIDO'), ('HERMANO', 'HERMANO'), ('ESPOSO', 'ESPOSO'), ('TIOS', 'TIOS'), ('ABUELOS', 'ABUELOS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='menor',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='menor',
            name='parentesco',
            field=models.CharField(default='HIJO', max_length=15),
        ),
        migrations.AlterField(
            model_name='menor',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=20),
        ),
    ]
