# Generated by Django 5.0.3 on 2024-07-05 16:45

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0004_remove_nutricional_agua_botellon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutricional',
            old_name='vegelales',
            new_name='poco_vegelales',
        ),
        migrations.AddField(
            model_name='nutricional',
            name='poco_frutas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Por Rechazo', 'Por Rechazo'), ('No sabe prepararlo', 'No sabe prepararlo'), ('Están muy costosos', 'Están muy costosos'), ('No están acostumbrados', 'No están acostumbrados')], max_length=200),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='poco_viceras',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Por Rechazo', 'Por Rechazo'), ('No sabe prepararlo', 'No sabe prepararlo'), ('Están muy costosos', 'Están muy costosos'), ('No están acostumbrados', 'No están acostumbrados')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frutas',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='viceras',
            field=models.CharField(blank=True, choices=[('0/7', '0/7'), ('1-2/7', '1-2/7'), ('3-5/7', '3-5/7'), ('7/7', '7/7'), ('1-2/15', '1-2/15'), ('1-2/30', '1-2/30')], max_length=10),
        ),
    ]
