# Generated by Django 5.0.3 on 2024-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0004_tarea_fecha_fin_tarea_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
