# Generated by Django 5.0.3 on 2024-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_alter_antropbef_proyecto_alter_antropmenor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropbef',
            name='max_imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='antropbef',
            name='min_imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
