# Generated by Django 5.0.3 on 2024-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_rename_vegelales_nutricional_poco_vegelales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricional',
            name='embarazo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('Poca Información ', 'Poca Información '), ('No Aplica', 'No Aplica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embarazada',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
    ]
