# Generated by Django 5.0.3 on 2024-10-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='completado',
            new_name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='importante',
        ),
    ]
