# Generated by Django 5.0.3 on 2024-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_alter_proyecto_options_alter_beneficiario_educacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=20),
        ),
    ]
