# Generated by Django 5.0.3 on 2024-09-10 11:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_remove_medica_asesoria_remove_medica_lacktokiana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='recomendaciones1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Asesoria en Lactancia', 'Asesoria en Lactancia'), ('Asesoria Nutricional', 'Asesoria Nutricional'), ('Referencia Psicológica', 'Referencia Psicológica')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='recomendaciones2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vitaminas', 'Vitaminas'), ('Lacktokiana', 'Lacktokiana'), ('ProKids', 'ProKids')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
