# Generated by Django 5.0.3 on 2024-06-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0005_alter_antropbef_peso_alter_beneficiario_educacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='abcesos',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='alergia',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='antiviotico',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_antiviotico',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_folico',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_hierro',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_leche',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_minerales',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cantidad_vitamina',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='caries',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='cefalea',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='dermatitis',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='diarreas',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='faringoamigdalitis',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='folico',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='hierro',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='hiperactividad',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='infeccion',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='leche',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='minerales',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='otitis',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='otros',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='parasitosis',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='sano',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='sinusitis',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='traumatismo',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='vitamina',
        ),
        migrations.AddField(
            model_name='medica',
            name='anemico',
            field=models.CharField(blank=True, choices=[('Suplementación de Acido Folico', 'Suplementación de Acido Folico'), ('Suplementación de Hierro', 'Suplementación de Hierro'), ('Suplementación de Minerales y Vitaminas', 'Suplementación de Minerales y Vitaminas')], max_length=50),
        ),
        migrations.AddField(
            model_name='medica',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('Niño Sano', 'Niño Sano'), ('Traumatismos varios', 'Traumatismos varios'), ('Alérgia', 'Alérgia'), ('Cefalea', 'Cefalea'), ('Hiperreactividad bronquial y rinitis', 'Hiperreactividad bronquial y rinitis'), ('Infección respiratoria inferior', 'Infección respiratoria inferior'), ('Faringoamigdalitis', 'Faringoamigdalitis'), ('Sinusitis', 'Sinusitis'), ('Parasitosis Intestinal', 'Parasitosis Intestinal'), ('Diarreas', 'Diarreas'), ('Dermatitis y otras afecciones de piel', 'Dermatitis y otras afecciones de piel'), ('Otitis', 'Otitis'), ('Caries dentales', 'Caries dentales'), ('Abscesos dentales', 'Abscesos dentales')], max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='educacion',
            field=models.CharField(blank=True, choices=[('ANALFABETA', 'ANALFABETA'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO MEDIO', 'TECNICO MEDIO'), ('TECNICO SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='embarazada',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='lactando',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='familia',
            name='educacion',
            field=models.CharField(blank=True, choices=[('ANALFABETA', 'ANALFABETA'), ('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO MEDIO', 'TECNICO MEDIO'), ('TECNICO SUPERIOR', 'TECNICO SUPERIOR'), ('UNIVERSITARIO', 'UNIVERSITARIO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='profesion',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='medica',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokitas.menor'),
        ),
        migrations.AlterField(
            model_name='menor',
            name='parentesco',
            field=models.CharField(choices=[('HIJO', 'HIJO'), ('HIJA', 'HIJA')], max_length=15),
        ),
        migrations.AlterField(
            model_name='menor',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=15),
        ),
    ]
