# Generated by Django 5.0.3 on 2024-08-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_antropbef_max_imc_antropbef_min_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropmenor',
            name='cc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='pse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='ptr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EGRESO', 'EGRESO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='menor',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EGRESO', 'EGRESO')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EGRESO', 'EGRESO')], max_length=10),
        ),
    ]
