# Generated by Django 5.0.3 on 2024-07-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_nutricional_embarazo_alter_nutricional_embarazada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricional',
            name='embarazada',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
