# Generated by Django 5.0.3 on 2024-10-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_rename_completado_tarea_fecha_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_final',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_inicio',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='titulo',
            new_name='title',
        ),
    ]
