# Generated by Django 5.0.3 on 2024-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_remove_medica_abcesos_remove_medica_alergia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='medica',
            name='diagnostico1',
            field=models.CharField(blank=True, choices=[('Niño Sano', 'Niño Sano'), ('Traumatismos varios', 'Traumatismos varios'), ('Alérgia', 'Alérgia'), ('Cefalea', 'Cefalea'), ('Hiperreactividad bronquial y rinitis', 'Hiperreactividad bronquial y rinitis')], max_length=50),
        ),
        migrations.AddField(
            model_name='medica',
            name='diagnostico2',
            field=models.CharField(blank=True, choices=[('Infección respiratoria inferior', 'Infección respiratoria inferior'), ('Faringoamigdalitis', 'Faringoamigdalitis'), ('Sinusitis', 'Sinusitis'), ('Parasitosis Intestinal', 'Parasitosis Intestinal'), ('Diarreas', 'Diarreas')], max_length=50),
        ),
        migrations.AddField(
            model_name='medica',
            name='diagnostico3',
            field=models.CharField(blank=True, choices=[('Dermatitis y otras afecciones de piel', 'Dermatitis y otras afecciones de piel'), ('Otitis', 'Otitis'), ('Caries dentales', 'Caries dentales'), ('Abscesos dentales', 'Abscesos dentales')], max_length=50),
        ),
    ]
