# Generated by Django 5.0.3 on 2024-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_alter_medica_recomendaciones1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menor',
            name='cbi_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='cc_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='diagnostico_inicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menor',
            name='diagnostico_talla_inicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menor',
            name='imc_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='peso_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='pse_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='ptr_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menor',
            name='talla_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menor',
            name='diagnostico_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
