# Generated by Django 5.0.3 on 2024-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0006_alter_familia_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='laboral',
            field=models.CharField(blank=True, choices=[('DESEMPLEADO', 'DESEMPLEADO'), ('EMPLEADO', 'EMPLEADO'), ('OCACIONAL', 'OCACIONAL'), ('INDEPENDIENTE', 'INDEPENDIENTE')], max_length=20),
        ),
    ]
