# Generated by Django 5.0.3 on 2024-09-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_menor_cbi_inicial_menor_cc_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='recomendaciones1',
        ),
        migrations.AddField(
            model_name='medica',
            name='asesor_lactancia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='recomen_nutricional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='refe_psicologica',
            field=models.BooleanField(default=False),
        ),
    ]
