# Generated by Django 5.0.3 on 2024-07-07 18:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_alter_nutricional_embarazada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutricional',
            old_name='poco_vegelales',
            new_name='poco_vegetales',
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='actividad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='almacena_agua',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='apetito',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='bonos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='carnes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='cereales',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='charcuteria',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='clap',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='compra_agua',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='compra_gas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_beneficio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_calidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_desnutricion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='conoce_grupos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='cuantas_comidas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='cuantos_grupos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='desea_amamantar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='desea_conocimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='desea_orientacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='dificultad_amamantar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embarazada',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embarazo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embutidos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='familiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frutas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='grasas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='huevos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='iglesia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lactando',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lactante',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lacteos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='leguminosas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='medicamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='medicamento_suplemento',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='meriendas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pensionado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pescado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pollo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='practica_deporte',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tiempo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tipo_grupos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cereales y Leguminosas', 'Cereales y Leguminosas'), ('Frutas y Verduras', 'Frutas y Verduras'), ('Leche, Yogures y Quesos', 'Leche, Yogures y Quesos'), ('Grasas y Aceites', 'Grasas y Aceites'), ('Dulces', 'Dulces'), ('Carnes y Huevos', 'Carnes y Huevos')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tuberculos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='vegetales',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='viceras',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
