# Generated by Django 5.0.3 on 2024-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_remove_medica_diagnostico_medica_diagnostico1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='desp_familia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medica',
            name='desp_menor',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
    ]
