# Generated by Django 5.0.3 on 2024-10-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_rename_fecha_final_tarea_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
