# Generated by Django 5.0.3 on 2024-03-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_alter_familia_laboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('cedula_bef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokitas.beneficiario')),
            ],
        ),
    ]
