# Generated by Django 5.0.3 on 2024-08-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0007_alter_antropmenor_cc_alter_antropmenor_pse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.proyecto')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
