# Generated by Django 5.0.3 on 2024-08-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_jornada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ('-jornada',)},
        ),
        migrations.RenameField(
            model_name='jornada',
            old_name='fecha',
            new_name='jornada',
        ),
        migrations.RemoveField(
            model_name='antropbef',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='antropmenor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='nutricional',
            name='fecha',
        ),
        migrations.AddField(
            model_name='antropbef',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='antropmenor',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='medica',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.proyecto'),
        ),
        migrations.AddField(
            model_name='menor',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
        migrations.AlterField(
            model_name='medica',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.proyecto'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_bef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokitas.beneficiario')),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.proyecto')),
            ],
            options={
                'ordering': ('-jornada',),
            },
        ),
    ]
