# Generated by Django 5.0.3 on 2024-10-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_alter_tarea_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='anemico',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='diagnostico1',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='diagnostico2',
        ),
        migrations.RemoveField(
            model_name='medica',
            name='diagnostico3',
        ),
    ]
