# Generated by Django 5.0.3 on 2024-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_alter_medica_desp_familia_alter_medica_desp_menor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='anemico',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
