# Generated by Django 5.0.3 on 2024-07-12 16:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_rename_poco_vegelales_nutricional_poco_vegetales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutricional',
            old_name='embarazada',
            new_name='en_embarazo',
        ),
        migrations.RenameField(
            model_name='nutricional',
            old_name='lactante',
            new_name='en_lactando',
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='agua',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tuberia sin Tratamiento', 'Tuberia sin Tratamiento'), ('Filtrada', 'Filtrada'), ('Botellon', 'Botellon'), ('Hervida', 'Hervida'), ('Tabletas Aguatab', 'Tabletas Aguatab')], max_length=200),
        ),
    ]
