# Generated by Django 5.0.3 on 2024-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_remove_medica_recomendaciones1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medica',
            name='recomendaciones2',
        ),
        migrations.AddField(
            model_name='medica',
            name='lacktokiana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='prokids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='vitaminas',
            field=models.BooleanField(default=False),
        ),
    ]
