# Generated by Django 5.0.3 on 2024-03-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0008_medicamentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicamentos',
            new_name='Medicamento',
        ),
    ]
