# Generated by Django 5.0.3 on 2024-09-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0009_remove_medica_recomendaciones2_medica_lacktokiana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(choices=[('Pfizer', 'Pfizer'), ('Moderna', 'Moderna'), ('Astrazeneca', 'Astrazeneca'), ('Janssen', 'Janssen'), ('Sin vacuna', 'Sin vacuna')], max_length=20)),
                ('descripcion', models.CharField(choices=[('1ra DOSIS', '1ra DOSIS'), ('2da DOSIS', '2da DOSIS'), ('3ra DOSIS', '3ra DOSIS'), ('4ra DOSIS', '4ra DOSIS'), ('5ra DOSIS', '5ra DOSIS'), ('REFUERZO 1ra DOSIS', 'REFUERZO 1ra DOSIS'), ('REFUERZO 2da DOSIS', 'REFUERZO 2da DOSIS'), ('REFUERZO 3ra DOSIS', 'REFUERZO 3ra DOSIS')], max_length=20)),
                ('creado', models.DateField(auto_now_add=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokitas.menor')),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.proyecto')),
            ],
        ),
    ]
