# Generated by Django 5.0.3 on 2024-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0009_alter_medica_anemico_alter_medica_diagnostico1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='anemico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
