# Generated by Django 5.0.3 on 2024-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0009_remove_medica_anemico_remove_medica_diagnostico1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medica',
            name='abscesos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='alergia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='caries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='cefalea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='dermatitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='diarreas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='faringoamigdalitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='folico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='hierro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='infeccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='minerales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='otitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='parasitosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='rinitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='sano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='sinusitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medica',
            name='traumatismo',
            field=models.BooleanField(default=False),
        ),
    ]
