# Generated by Django 5.0.3 on 2024-07-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0009_rename_embarazada_nutricional_en_embarazo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='lactando',
            new_name='lactante',
        ),
    ]
