# Generated by Django 5.0.3 on 2024-06-26 09:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0010_alter_medica_anemico_alter_medica_diagnostico1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='anemico',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Suplementación de Acido Folico', 'Suplementación de Acido Folico'), ('Suplementación de Hierro', 'Suplementación de Hierro'), ('Suplementación de Minerales y Vitaminas', 'Suplementación de Minerales y Vitaminas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Niño Sano', 'Niño Sano'), ('Traumatismos varios', 'Traumatismos varios'), ('Alérgia', 'Alérgia'), ('Cefalea', 'Cefalea'), ('Hiperreactividad bronquial y rinitis', 'Hiperreactividad bronquial y rinitis')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Infección respiratoria inferior', 'Infección respiratoria inferior'), ('Faringoamigdalitis', 'Faringoamigdalitis'), ('Sinusitis', 'Sinusitis'), ('Parasitosis Intestinal', 'Parasitosis Intestinal'), ('Diarreas', 'Diarreas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='medica',
            name='diagnostico3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dermatitis y otras afecciones de piel', 'Dermatitis y otras afecciones de piel'), ('Otitis', 'Otitis'), ('Caries dentales', 'Caries dentales'), ('Abscesos dentales', 'Abscesos dentales')], max_length=200),
        ),
    ]
