# Generated by Django 5.0.3 on 2024-11-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0010_medica_abscesos_medica_alergia_medica_caries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricional',
            name='carnes',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='cereales',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='charcuteria',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='embutidos',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='frutas',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='grasas',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='huevos',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='lacteos',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='leguminosas',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pescado',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='pollo',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='tuberculos',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='vegetales',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='viceras',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
