# Generated by Django 5.0.3 on 2024-08-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0010_rename_ciudad_ciudades_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudades',
            old_name='d_estado',
            new_name='id_estado',
        ),
    ]
