# Generated by Django 5.0.3 on 2024-07-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0010_rename_lactando_beneficiario_lactante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socioeconomico',
        ),
    ]
