# Generated by Django 5.0.3 on 2024-11-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0011_alter_nutricional_carnes_alter_nutricional_cereales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricional',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokitas.jornada'),
        ),
    ]
