# Generated by Django 5.0.3 on 2024-08-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0011_rename_d_estado_ciudades_id_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudades',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
