# Generated by Django 5.0.3 on 2024-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0011_delete_socioeconomico'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropmenor',
            name='maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='antropmenor',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='color1',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='color2',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='color3',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='color4',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='color5',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
