# Generated by Django 5.0.3 on 2024-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0012_alter_medica_diagnostico1_alter_medica_diagnostico2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medica',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medica',
            name='meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='antropbef',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='antropbef',
            name='meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='antropmenor',
            name='meses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
