# Generated by Django 5.0.3 on 2024-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0012_antropmenor_maximo_antropmenor_minimo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antropmenor',
            old_name='maximo',
            new_name='max_peso',
        ),
        migrations.RenameField(
            model_name='antropmenor',
            old_name='minimo',
            new_name='max_talla',
        ),
        migrations.AddField(
            model_name='antropmenor',
            name='min_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='antropmenor',
            name='min_talla',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
