# Generated by Django 5.0.3 on 2024-11-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0012_alter_nutricional_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricional',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokitas.jornada'),
        ),
    ]
