# Generated by Django 5.0.3 on 2024-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0012_delete_ciudades_delete_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antropbef',
            name='cbi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='antropbef',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='antropbef',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO'), ('EGRESO', 'EGRESO'), ('DESINCORPORACION', 'DESINCORPORACION')], default='ACTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='menor',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO'), ('EGRESO', 'EGRESO'), ('DESINCORPORACION', 'DESINCORPORACION')], default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO'), ('EGRESO', 'EGRESO'), ('DESINCORPORACION', 'DESINCORPORACION')], max_length=30),
        ),
    ]
