# Generated by Django 5.0.3 on 2024-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokitas', '0013_medica_edad_medica_meses_alter_antropbef_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medica',
            name='proyecto',
            field=models.CharField(max_length=50),
        ),
    ]
